use analysis;
select*from customer limit 20;
ALTER TABLE customer 
RENAME COLUMN `purchase_amount_(usd)` TO purchase_amount;

-- Q1. Total reveune generated by male vs female customers
SELECT 
    gender, 
    SUM(purchase_amount) AS gender_wise_revenue 
FROM 
    customer 
GROUP BY 
    gender;
-- Q2.Which customers used a discount but still spent more than the avg purchase amount
SELECT 
    customer_id, 
    purchase_amount
FROM 
    customer 
WHERE 
    discount_applied = 'Yes' and purchase_amount >=(select avg(purchase_amount)from customer);
    
-- Q3.Top 5 products with higgest avg review_rating
select item_purchased,avg(review_rating) as "average product rating" from customer group by item_purchased
order by avg(review_rating) desc  limit 5;

-- Q4 compare the avg purchased amount between standrad and express shipping 
select shipping_type ,avg(purchase_amount) from customer WHERE shipping_type IN ('Standard', 'Express') group by shipping_type ;

-- Q5 DO subscribed customers spend more? compare avg spend,total revenue betn subscriber and non subscriber
select subscription_status, avg(purchase_amount) as 'avg_spending' from customer group by subscription_status;
select subscription_status, sum(purchase_amount) as 'total_revenue' from customer group by subscription_status;

-- Q6 which 5 products have higghest percentage of purchases with discount applied 
select item_purchased ,
sum(case when discount_applied ='Yes' then 1 else 0 end )/count(*)*100 as discount_rate from customer group by  item_purchased order by discount_rate desc limit 5;

-- Q7 Segment customers into new , returning and loyal based on their total number of previous purchases and show of each segment 
WITH customer_type AS (
    SELECT 
        customer_id,
        previous_purchases,
        CASE
            WHEN previous_purchases = 1 THEN 'New'
            WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returning'
            ELSE 'Loyal'
        END AS customer_segment
    FROM customer
)
SELECT 
    customer_segment, 
    COUNT(*) AS `Number of customers`
FROM customer_type 
GROUP BY customer_segment;

-- Q8 Are customers who are repeat buyers(more than 5 previous purchases ) also subcribers?
select subscription_status , count(customer_id) as repeat_buyers from customer where previous_purchases >5 group by subscription_status ; 

-- Q9 Revenue by age group 
select age_group ,sum(purchase_amount) as Renevue_by_age_group from customer group by age_group order by sum(purchase_amount) desc;
select *from customer
